<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>default</LangVersion>
    <DebugType>embedded</DebugType>

    <EnableDynamicLoading>true</EnableDynamicLoading>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LoupixDeck.PluginSdk" Version="1.24.0">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Tmds.DBus.Protocol" Version="0.95.1" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="KWinBridgeScript.js" />
  </ItemGroup>

</Project>
